// playground/ssr/src/storyblok/react/Counter.jsx
import { useState } from 'react';

export default function Counter(props) {
  const [count, setCount] = useState(0);
  const add = () => setCount(i => i + 1);
  const subtract = () => setCount(i => i - 1);

  return (
    <>
      <div className="counter">
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div className="counter-message">{props.blok.headline}</div>
    </>
  );
}

// playground-ssr/src/storyblok/vue/Counter.vue
<template>
  <div class="counter">
    <button @click="subtract()">-</button>
    <pre>{{ count }}</pre>
    <button @click="add()">+</button>
  </div>
  <div class="counter-message">
    {{ blok.headline }}
  </div>
</template>

<script setup>
import { ref } from "vue";
defineProps({ blok: Object });
const count = ref(0);
const add = () => (count.value = count.value + 1);
const subtract = () => (count.value = count.value - 1);
</script>

<style>
.counter {
  display: grid;
  font-size: 2em;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  margin-top: 2em;
  place-items: center;
}
.counter-message {
  text-align: center;
}
</style>
